name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  ci:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - run: go test ./...
